### ISSUE TITLE
Use parking lot?

### ISSUE THREAD

**Issue by SchrodingerZhu** [project-scott/scottdb#1]
According to my benchmark (a quadtree with multithread update), facilities in parking_lot are much faster than std.

**Comment by SchrodingerZhu** [comment]
You may need to use nightly rust to gain the speedup though. As HLE feature is only supported in nightly

**Comment by chuigda** [comment]
The synchronization manners are all considered temporary, we will introduce MVCC in further commits. What's more, I wouldn't like much external dependencies, while the performance of rust std may get better as time goes by.
